#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityManager.App_Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ActivityManager")]
	public partial class ActivityManagerDataContext : System.Data.Linq.DataContext
	{
		private static string conStr = "Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=D:\\docs\\Desktop\\ActivityManager\\App_Data\\ActivityManager.mdf;Integrated Security=True";

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertActivity(Activity instance);
    partial void UpdateActivity(Activity instance);
    partial void DeleteActivity(Activity instance);
    partial void InsertStudentIdentified(StudentIdentified instance);
    partial void UpdateStudentIdentified(StudentIdentified instance);
    partial void DeleteStudentIdentified(StudentIdentified instance);
    partial void InsertAdministration(Administration instance);
    partial void UpdateAdministration(Administration instance);
    partial void DeleteAdministration(Administration instance);
    partial void InsertLikedActivity(LikedActivity instance);
    partial void UpdateLikedActivity(LikedActivity instance);
    partial void DeleteLikedActivity(LikedActivity instance);
    partial void InsertOrganization(Organization instance);
    partial void UpdateOrganization(Organization instance);
    partial void DeleteOrganization(Organization instance);
    partial void InsertPlace(Place instance);
    partial void UpdatePlace(Place instance);
    partial void DeletePlace(Place instance);
    partial void InsertSignedActivity(SignedActivity instance);
    partial void UpdateSignedActivity(SignedActivity instance);
    partial void DeleteSignedActivity(SignedActivity instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    #endregion
		
		public ActivityManagerDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

        public ActivityManagerDataContext() :
        base(conStr, mappingSource)
        {
            OnCreated();
        }

        public ActivityManagerDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ActivityManagerDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ActivityManagerDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Activity> Activity
		{
			get
			{
				return this.GetTable<Activity>();
			}
		}
		
		public System.Data.Linq.Table<StudentIdentified> StudentIdentified
		{
			get
			{
				return this.GetTable<StudentIdentified>();
			}
		}
		
		public System.Data.Linq.Table<Administration> Administration
		{
			get
			{
				return this.GetTable<Administration>();
			}
		}
		
		public System.Data.Linq.Table<LikedActivity> LikedActivity
		{
			get
			{
				return this.GetTable<LikedActivity>();
			}
		}
		
		public System.Data.Linq.Table<Organization> Organization
		{
			get
			{
				return this.GetTable<Organization>();
			}
		}
		
		public System.Data.Linq.Table<Place> Place
		{
			get
			{
				return this.GetTable<Place>();
			}
		}
		
		public System.Data.Linq.Table<SignedActivity> SignedActivity
		{
			get
			{
				return this.GetTable<SignedActivity>();
			}
		}
		
		public System.Data.Linq.Table<Student> Student
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Activity")]
	public partial class Activity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _activityID;
		
		private string _activityName;
		
		private string _activityIntro;
		
		private System.Nullable<int> _activityPlaceID;
		
		private string _activityOrgID;
		
		private System.Nullable<int> _availableCredit;
		
		private System.Nullable<int> _maxSigned;
		
		private System.Nullable<int> _signed;
		
		private System.Nullable<int> _activityState;
		
		private System.Nullable<System.DateTime> _signStartDate;
		
		private System.Nullable<System.DateTime> _signEndDate;
		
		private System.Nullable<System.DateTime> _holdDate;
		
		private System.Nullable<int> _holdStart;
		
		private System.Nullable<int> _holdEnd;
		
		private System.Nullable<System.DateTime> _submitTime;
		
		private string _failReason;
		
		private EntitySet<LikedActivity> _LikedActivity;
		
		private EntitySet<SignedActivity> _SignedActivity;
		
		private EntityRef<Organization> _Organization;
		
		private EntityRef<Place> _Place;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnactivityIDChanging(string value);
    partial void OnactivityIDChanged();
    partial void OnactivityNameChanging(string value);
    partial void OnactivityNameChanged();
    partial void OnactivityIntroChanging(string value);
    partial void OnactivityIntroChanged();
    partial void OnactivityPlaceIDChanging(System.Nullable<int> value);
    partial void OnactivityPlaceIDChanged();
    partial void OnactivityOrgIDChanging(string value);
    partial void OnactivityOrgIDChanged();
    partial void OnavailableCreditChanging(System.Nullable<int> value);
    partial void OnavailableCreditChanged();
    partial void OnmaxSignedChanging(System.Nullable<int> value);
    partial void OnmaxSignedChanged();
    partial void OnsignedChanging(System.Nullable<int> value);
    partial void OnsignedChanged();
    partial void OnactivityStateChanging(System.Nullable<int> value);
    partial void OnactivityStateChanged();
    partial void OnsignStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignStartDateChanged();
    partial void OnsignEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignEndDateChanged();
    partial void OnholdDateChanging(System.Nullable<System.DateTime> value);
    partial void OnholdDateChanged();
    partial void OnholdStartChanging(System.Nullable<int> value);
    partial void OnholdStartChanged();
    partial void OnholdEndChanging(System.Nullable<int> value);
    partial void OnholdEndChanged();
    partial void OnsubmitTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnsubmitTimeChanged();
    partial void OnfailReasonChanging(string value);
    partial void OnfailReasonChanged();
    #endregion
		
		public Activity()
		{
			this._LikedActivity = new EntitySet<LikedActivity>(new Action<LikedActivity>(this.attach_LikedActivity), new Action<LikedActivity>(this.detach_LikedActivity));
			this._SignedActivity = new EntitySet<SignedActivity>(new Action<SignedActivity>(this.attach_SignedActivity), new Action<SignedActivity>(this.detach_SignedActivity));
			this._Organization = default(EntityRef<Organization>);
			this._Place = default(EntityRef<Place>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string activityID
		{
			get
			{
				return this._activityID;
			}
			set
			{
				if ((this._activityID != value))
				{
					this.OnactivityIDChanging(value);
					this.SendPropertyChanging();
					this._activityID = value;
					this.SendPropertyChanged("activityID");
					this.OnactivityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityName", DbType="VarChar(30)")]
		public string activityName
		{
			get
			{
				return this._activityName;
			}
			set
			{
				if ((this._activityName != value))
				{
					this.OnactivityNameChanging(value);
					this.SendPropertyChanging();
					this._activityName = value;
					this.SendPropertyChanged("activityName");
					this.OnactivityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityIntro", DbType="VarChar(400)")]
		public string activityIntro
		{
			get
			{
				return this._activityIntro;
			}
			set
			{
				if ((this._activityIntro != value))
				{
					this.OnactivityIntroChanging(value);
					this.SendPropertyChanging();
					this._activityIntro = value;
					this.SendPropertyChanged("activityIntro");
					this.OnactivityIntroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityPlaceID", DbType="Int")]
		public System.Nullable<int> activityPlaceID
		{
			get
			{
				return this._activityPlaceID;
			}
			set
			{
				if ((this._activityPlaceID != value))
				{
					if (this._Place.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnactivityPlaceIDChanging(value);
					this.SendPropertyChanging();
					this._activityPlaceID = value;
					this.SendPropertyChanged("activityPlaceID");
					this.OnactivityPlaceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityOrgID", DbType="Char(13)")]
		public string activityOrgID
		{
			get
			{
				return this._activityOrgID;
			}
			set
			{
				if ((this._activityOrgID != value))
				{
					if (this._Organization.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnactivityOrgIDChanging(value);
					this.SendPropertyChanging();
					this._activityOrgID = value;
					this.SendPropertyChanged("activityOrgID");
					this.OnactivityOrgIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_availableCredit", DbType="Int")]
		public System.Nullable<int> availableCredit
		{
			get
			{
				return this._availableCredit;
			}
			set
			{
				if ((this._availableCredit != value))
				{
					this.OnavailableCreditChanging(value);
					this.SendPropertyChanging();
					this._availableCredit = value;
					this.SendPropertyChanged("availableCredit");
					this.OnavailableCreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxSigned", DbType="Int")]
		public System.Nullable<int> maxSigned
		{
			get
			{
				return this._maxSigned;
			}
			set
			{
				if ((this._maxSigned != value))
				{
					this.OnmaxSignedChanging(value);
					this.SendPropertyChanging();
					this._maxSigned = value;
					this.SendPropertyChanged("maxSigned");
					this.OnmaxSignedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signed", DbType="Int")]
		public System.Nullable<int> signed
		{
			get
			{
				return this._signed;
			}
			set
			{
				if ((this._signed != value))
				{
					this.OnsignedChanging(value);
					this.SendPropertyChanging();
					this._signed = value;
					this.SendPropertyChanged("signed");
					this.OnsignedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityState", DbType="Int")]
		public System.Nullable<int> activityState
		{
			get
			{
				return this._activityState;
			}
			set
			{
				if ((this._activityState != value))
				{
					this.OnactivityStateChanging(value);
					this.SendPropertyChanging();
					this._activityState = value;
					this.SendPropertyChanged("activityState");
					this.OnactivityStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signStartDate", DbType="Date")]
		public System.Nullable<System.DateTime> signStartDate
		{
			get
			{
				return this._signStartDate;
			}
			set
			{
				if ((this._signStartDate != value))
				{
					this.OnsignStartDateChanging(value);
					this.SendPropertyChanging();
					this._signStartDate = value;
					this.SendPropertyChanged("signStartDate");
					this.OnsignStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signEndDate", DbType="Date")]
		public System.Nullable<System.DateTime> signEndDate
		{
			get
			{
				return this._signEndDate;
			}
			set
			{
				if ((this._signEndDate != value))
				{
					this.OnsignEndDateChanging(value);
					this.SendPropertyChanging();
					this._signEndDate = value;
					this.SendPropertyChanged("signEndDate");
					this.OnsignEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_holdDate", DbType="Date")]
		public System.Nullable<System.DateTime> holdDate
		{
			get
			{
				return this._holdDate;
			}
			set
			{
				if ((this._holdDate != value))
				{
					this.OnholdDateChanging(value);
					this.SendPropertyChanging();
					this._holdDate = value;
					this.SendPropertyChanged("holdDate");
					this.OnholdDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_holdStart", DbType="Int")]
		public System.Nullable<int> holdStart
		{
			get
			{
				return this._holdStart;
			}
			set
			{
				if ((this._holdStart != value))
				{
					this.OnholdStartChanging(value);
					this.SendPropertyChanging();
					this._holdStart = value;
					this.SendPropertyChanged("holdStart");
					this.OnholdStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_holdEnd", DbType="Int")]
		public System.Nullable<int> holdEnd
		{
			get
			{
				return this._holdEnd;
			}
			set
			{
				if ((this._holdEnd != value))
				{
					this.OnholdEndChanging(value);
					this.SendPropertyChanging();
					this._holdEnd = value;
					this.SendPropertyChanged("holdEnd");
					this.OnholdEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_submitTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> submitTime
		{
			get
			{
				return this._submitTime;
			}
			set
			{
				if ((this._submitTime != value))
				{
					this.OnsubmitTimeChanging(value);
					this.SendPropertyChanging();
					this._submitTime = value;
					this.SendPropertyChanged("submitTime");
					this.OnsubmitTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_failReason", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string failReason
		{
			get
			{
				return this._failReason;
			}
			set
			{
				if ((this._failReason != value))
				{
					this.OnfailReasonChanging(value);
					this.SendPropertyChanging();
					this._failReason = value;
					this.SendPropertyChanged("failReason");
					this.OnfailReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Activity_LikedActivity", Storage="_LikedActivity", ThisKey="activityID", OtherKey="activityID")]
		public EntitySet<LikedActivity> LikedActivity
		{
			get
			{
				return this._LikedActivity;
			}
			set
			{
				this._LikedActivity.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Activity_SignedActivity", Storage="_SignedActivity", ThisKey="activityID", OtherKey="activityID")]
		public EntitySet<SignedActivity> SignedActivity
		{
			get
			{
				return this._SignedActivity;
			}
			set
			{
				this._SignedActivity.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Organization_Activity", Storage="_Organization", ThisKey="activityOrgID", OtherKey="organizationID", IsForeignKey=true)]
		public Organization Organization
		{
			get
			{
				return this._Organization.Entity;
			}
			set
			{
				Organization previousValue = this._Organization.Entity;
				if (((previousValue != value) 
							|| (this._Organization.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Organization.Entity = null;
						previousValue.Activity.Remove(this);
					}
					this._Organization.Entity = value;
					if ((value != null))
					{
						value.Activity.Add(this);
						this._activityOrgID = value.organizationID;
					}
					else
					{
						this._activityOrgID = default(string);
					}
					this.SendPropertyChanged("Organization");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Place_Activity", Storage="_Place", ThisKey="activityPlaceID", OtherKey="placeID", IsForeignKey=true)]
		public Place Place
		{
			get
			{
				return this._Place.Entity;
			}
			set
			{
				Place previousValue = this._Place.Entity;
				if (((previousValue != value) 
							|| (this._Place.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Place.Entity = null;
						previousValue.Activity.Remove(this);
					}
					this._Place.Entity = value;
					if ((value != null))
					{
						value.Activity.Add(this);
						this._activityPlaceID = value.placeID;
					}
					else
					{
						this._activityPlaceID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Place");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LikedActivity(LikedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Activity = this;
		}
		
		private void detach_LikedActivity(LikedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Activity = null;
		}
		
		private void attach_SignedActivity(SignedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Activity = this;
		}
		
		private void detach_SignedActivity(SignedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Activity = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StudentIdentified")]
	public partial class StudentIdentified : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _studentID;
		
		private string _studentPassword;
		
		private string _phone;
		
		private System.Nullable<int> _credit;
		
		private EntityRef<Student> _Student;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIDChanging(string value);
    partial void OnstudentIDChanged();
    partial void OnstudentPasswordChanging(string value);
    partial void OnstudentPasswordChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OncreditChanging(System.Nullable<int> value);
    partial void OncreditChanged();
    #endregion
		
		public StudentIdentified()
		{
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentPassword", DbType="VarChar(30)")]
		public string studentPassword
		{
			get
			{
				return this._studentPassword;
			}
			set
			{
				if ((this._studentPassword != value))
				{
					this.OnstudentPasswordChanging(value);
					this.SendPropertyChanging();
					this._studentPassword = value;
					this.SendPropertyChanged("studentPassword");
					this.OnstudentPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="Char(11)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credit", DbType="Int")]
		public System.Nullable<int> credit
		{
			get
			{
				return this._credit;
			}
			set
			{
				if ((this._credit != value))
				{
					this.OncreditChanging(value);
					this.SendPropertyChanging();
					this._credit = value;
					this.SendPropertyChanged("credit");
					this.OncreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StudentIdentified", Storage="_Student", ThisKey="studentID", OtherKey="studentID", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.StudentIdentified = null;
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.StudentIdentified = this;
						this._studentID = value.studentID;
					}
					else
					{
						this._studentID = default(string);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administration")]
	public partial class Administration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _adminID;
		
		private string _adminPassword;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminIDChanging(string value);
    partial void OnadminIDChanged();
    partial void OnadminPasswordChanging(string value);
    partial void OnadminPasswordChanged();
    #endregion
		
		public Administration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string adminID
		{
			get
			{
				return this._adminID;
			}
			set
			{
				if ((this._adminID != value))
				{
					this.OnadminIDChanging(value);
					this.SendPropertyChanging();
					this._adminID = value;
					this.SendPropertyChanged("adminID");
					this.OnadminIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminPassword", DbType="VarChar(30)")]
		public string adminPassword
		{
			get
			{
				return this._adminPassword;
			}
			set
			{
				if ((this._adminPassword != value))
				{
					this.OnadminPasswordChanging(value);
					this.SendPropertyChanging();
					this._adminPassword = value;
					this.SendPropertyChanged("adminPassword");
					this.OnadminPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LikedActivity")]
	public partial class LikedActivity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _studentID;
		
		private string _activityID;
		
		private EntityRef<Activity> _Activity;
		
		private EntityRef<Student> _Student;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIDChanging(string value);
    partial void OnstudentIDChanged();
    partial void OnactivityIDChanging(string value);
    partial void OnactivityIDChanged();
    #endregion
		
		public LikedActivity()
		{
			this._Activity = default(EntityRef<Activity>);
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string activityID
		{
			get
			{
				return this._activityID;
			}
			set
			{
				if ((this._activityID != value))
				{
					if (this._Activity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnactivityIDChanging(value);
					this.SendPropertyChanging();
					this._activityID = value;
					this.SendPropertyChanged("activityID");
					this.OnactivityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Activity_LikedActivity", Storage="_Activity", ThisKey="activityID", OtherKey="activityID", IsForeignKey=true)]
		public Activity Activity
		{
			get
			{
				return this._Activity.Entity;
			}
			set
			{
				Activity previousValue = this._Activity.Entity;
				if (((previousValue != value) 
							|| (this._Activity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Activity.Entity = null;
						previousValue.LikedActivity.Remove(this);
					}
					this._Activity.Entity = value;
					if ((value != null))
					{
						value.LikedActivity.Add(this);
						this._activityID = value.activityID;
					}
					else
					{
						this._activityID = default(string);
					}
					this.SendPropertyChanged("Activity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_LikedActivity", Storage="_Student", ThisKey="studentID", OtherKey="studentID", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.LikedActivity.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.LikedActivity.Add(this);
						this._studentID = value.studentID;
					}
					else
					{
						this._studentID = default(string);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Organization")]
	public partial class Organization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _organizationID;
		
		private string _organizationName;
		
		private string _organizationPassword;
		
		private EntitySet<Activity> _Activity;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnorganizationIDChanging(string value);
    partial void OnorganizationIDChanged();
    partial void OnorganizationNameChanging(string value);
    partial void OnorganizationNameChanged();
    partial void OnorganizationPasswordChanging(string value);
    partial void OnorganizationPasswordChanged();
    #endregion
		
		public Organization()
		{
			this._Activity = new EntitySet<Activity>(new Action<Activity>(this.attach_Activity), new Action<Activity>(this.detach_Activity));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationID", DbType="Char(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string organizationID
		{
			get
			{
				return this._organizationID;
			}
			set
			{
				if ((this._organizationID != value))
				{
					this.OnorganizationIDChanging(value);
					this.SendPropertyChanging();
					this._organizationID = value;
					this.SendPropertyChanged("organizationID");
					this.OnorganizationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationName", DbType="VarChar(20)")]
		public string organizationName
		{
			get
			{
				return this._organizationName;
			}
			set
			{
				if ((this._organizationName != value))
				{
					this.OnorganizationNameChanging(value);
					this.SendPropertyChanging();
					this._organizationName = value;
					this.SendPropertyChanged("organizationName");
					this.OnorganizationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_organizationPassword", DbType="VarChar(30)")]
		public string organizationPassword
		{
			get
			{
				return this._organizationPassword;
			}
			set
			{
				if ((this._organizationPassword != value))
				{
					this.OnorganizationPasswordChanging(value);
					this.SendPropertyChanging();
					this._organizationPassword = value;
					this.SendPropertyChanged("organizationPassword");
					this.OnorganizationPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Organization_Activity", Storage="_Activity", ThisKey="organizationID", OtherKey="activityOrgID")]
		public EntitySet<Activity> Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				this._Activity.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Activity(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Organization = this;
		}
		
		private void detach_Activity(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Organization = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Place")]
	public partial class Place : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _placeID;
		
		private string _placeName;
		
		private int _volume;
		
		private EntitySet<Activity> _Activity;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnplaceIDChanging(int value);
    partial void OnplaceIDChanged();
    partial void OnplaceNameChanging(string value);
    partial void OnplaceNameChanged();
    partial void OnvolumeChanging(int value);
    partial void OnvolumeChanged();
    #endregion
		
		public Place()
		{
			this._Activity = new EntitySet<Activity>(new Action<Activity>(this.attach_Activity), new Action<Activity>(this.detach_Activity));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int placeID
		{
			get
			{
				return this._placeID;
			}
			set
			{
				if ((this._placeID != value))
				{
					this.OnplaceIDChanging(value);
					this.SendPropertyChanging();
					this._placeID = value;
					this.SendPropertyChanged("placeID");
					this.OnplaceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placeName", DbType="VarChar(20)")]
		public string placeName
		{
			get
			{
				return this._placeName;
			}
			set
			{
				if ((this._placeName != value))
				{
					this.OnplaceNameChanging(value);
					this.SendPropertyChanging();
					this._placeName = value;
					this.SendPropertyChanged("placeName");
					this.OnplaceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume", DbType="Int NOT NULL")]
		public int volume
		{
			get
			{
				return this._volume;
			}
			set
			{
				if ((this._volume != value))
				{
					this.OnvolumeChanging(value);
					this.SendPropertyChanging();
					this._volume = value;
					this.SendPropertyChanged("volume");
					this.OnvolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Place_Activity", Storage="_Activity", ThisKey="placeID", OtherKey="activityPlaceID")]
		public EntitySet<Activity> Activity
		{
			get
			{
				return this._Activity;
			}
			set
			{
				this._Activity.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Activity(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Place = this;
		}
		
		private void detach_Activity(Activity entity)
		{
			this.SendPropertyChanging();
			entity.Place = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SignedActivity")]
	public partial class SignedActivity : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _studentID;
		
		private string _activityID;
		
		private EntityRef<Activity> _Activity;
		
		private EntityRef<Student> _Student;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIDChanging(string value);
    partial void OnstudentIDChanged();
    partial void OnactivityIDChanging(string value);
    partial void OnactivityIDChanged();
    #endregion
		
		public SignedActivity()
		{
			this._Activity = default(EntityRef<Activity>);
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activityID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string activityID
		{
			get
			{
				return this._activityID;
			}
			set
			{
				if ((this._activityID != value))
				{
					if (this._Activity.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnactivityIDChanging(value);
					this.SendPropertyChanging();
					this._activityID = value;
					this.SendPropertyChanged("activityID");
					this.OnactivityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Activity_SignedActivity", Storage="_Activity", ThisKey="activityID", OtherKey="activityID", IsForeignKey=true)]
		public Activity Activity
		{
			get
			{
				return this._Activity.Entity;
			}
			set
			{
				Activity previousValue = this._Activity.Entity;
				if (((previousValue != value) 
							|| (this._Activity.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Activity.Entity = null;
						previousValue.SignedActivity.Remove(this);
					}
					this._Activity.Entity = value;
					if ((value != null))
					{
						value.SignedActivity.Add(this);
						this._activityID = value.activityID;
					}
					else
					{
						this._activityID = default(string);
					}
					this.SendPropertyChanged("Activity");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_SignedActivity", Storage="_Student", ThisKey="studentID", OtherKey="studentID", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.SignedActivity.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.SignedActivity.Add(this);
						this._studentID = value.studentID;
					}
					else
					{
						this._studentID = default(string);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _studentID;
		
		private string _ID;
		
		private string _studentName;
		
		private string _gender;
		
		private string _major;
		
		private string _class;
		
		private EntityRef<StudentIdentified> _StudentIdentified;
		
		private EntitySet<LikedActivity> _LikedActivity;
		
		private EntitySet<SignedActivity> _SignedActivity;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentIDChanging(string value);
    partial void OnstudentIDChanged();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnstudentNameChanging(string value);
    partial void OnstudentNameChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnmajorChanging(string value);
    partial void OnmajorChanged();
    partial void OnclassChanging(string value);
    partial void OnclassChanged();
    #endregion
		
		public Student()
		{
			this._StudentIdentified = default(EntityRef<StudentIdentified>);
			this._LikedActivity = new EntitySet<LikedActivity>(new Action<LikedActivity>(this.attach_LikedActivity), new Action<LikedActivity>(this.detach_LikedActivity));
			this._SignedActivity = new EntitySet<SignedActivity>(new Action<SignedActivity>(this.attach_SignedActivity), new Action<SignedActivity>(this.detach_SignedActivity));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Char(18)")]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentName", DbType="VarChar(22) NOT NULL", CanBeNull=false)]
		public string studentName
		{
			get
			{
				return this._studentName;
			}
			set
			{
				if ((this._studentName != value))
				{
					this.OnstudentNameChanging(value);
					this.SendPropertyChanging();
					this._studentName = value;
					this.SendPropertyChanged("studentName");
					this.OnstudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="Char(2)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_major", DbType="VarChar(26)")]
		public string major
		{
			get
			{
				return this._major;
			}
			set
			{
				if ((this._major != value))
				{
					this.OnmajorChanging(value);
					this.SendPropertyChanging();
					this._major = value;
					this.SendPropertyChanged("major");
					this.OnmajorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="class", Storage="_class", DbType="VarChar(10)")]
		public string @class
		{
			get
			{
				return this._class;
			}
			set
			{
				if ((this._class != value))
				{
					this.OnclassChanging(value);
					this.SendPropertyChanging();
					this._class = value;
					this.SendPropertyChanged("@class");
					this.OnclassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_StudentIdentified", Storage="_StudentIdentified", ThisKey="studentID", OtherKey="studentID", IsUnique=true, IsForeignKey=false)]
		public StudentIdentified StudentIdentified
		{
			get
			{
				return this._StudentIdentified.Entity;
			}
			set
			{
				StudentIdentified previousValue = this._StudentIdentified.Entity;
				if (((previousValue != value) 
							|| (this._StudentIdentified.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StudentIdentified.Entity = null;
						previousValue.Student = null;
					}
					this._StudentIdentified.Entity = value;
					if ((value != null))
					{
						value.Student = this;
					}
					this.SendPropertyChanged("StudentIdentified");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_LikedActivity", Storage="_LikedActivity", ThisKey="studentID", OtherKey="studentID")]
		public EntitySet<LikedActivity> LikedActivity
		{
			get
			{
				return this._LikedActivity;
			}
			set
			{
				this._LikedActivity.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_SignedActivity", Storage="_SignedActivity", ThisKey="studentID", OtherKey="studentID")]
		public EntitySet<SignedActivity> SignedActivity
		{
			get
			{
				return this._SignedActivity;
			}
			set
			{
				this._SignedActivity.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LikedActivity(LikedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_LikedActivity(LikedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
		
		private void attach_SignedActivity(SignedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_SignedActivity(SignedActivity entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
	}
}
#pragma warning restore 1591
